apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: webestebanpipelinessampleapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webestebanpipelinessampleapp 
    spec:
      containers:
        - name: webestebanpipelinessampleapp 
          image: acrtestingcontainer.azurecr.io/webestebanpipelinessampleapp
          ports:
          - containerPort: 8080